[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project]
name = "edmkit-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edmkit==0.0.4",
    "line-profiler>=5.0.0",
    "matplotlib>=3.10.8",
    "opentelemetry-api==1.39.1",
    "opentelemetry-exporter-otlp-proto-http==1.39.1",
    "opentelemetry-sdk==1.39.1",
    "polars>=1.37.1",
    "scipy>=1.15.1",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = ["hypothesis>=6.151.5", "pytest>=9.0.2", "ruff>=0.14.14", "ty>=0.0.13"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-x --tb=short"

[tool.uv.build-backend]
module-name = "edmkit.search"
